title: Casos prácticos de Inteligencia Artificial 
author: Javier Álvarez Osuna
logo: logo.png
copyright: "Feeding Systems S.L. - GNU General Public License 2025"

execute:
  execute_notebooks: force
  kernel_name: python3
  timeout: 300
  allow_errors: false
  cache: ""

build:
  build_directory: "_build"
  exclude_patterns: 
    - "**.ipynb_checkpoints"
    - "**/.DS_Store"
  create_plots: true

latex:
  latex_documents:
    targetname: IAbook.tex
  latex_engine: pdflatex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/jalosu/FFF-IA-book
  path_to_book: ""
  branch: master

html:
  extra_footer: ""
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false
  favicon: logo.png
  baseurl: ""
  analitics:
    google_analytics_id: ""

parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_image
    - dollarmath
    - amsmath

sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
    - myst_nb
  config:
    numfig: true
    source_suffix: [".md", ".ipynb"]
    mathjax3_config:
      tex:
        inlineMath: [['$', '$'], ['\(', '\)']]
